// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 服务器时间
type ServerTime struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Year                 int32    `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,4,opt,name=day,proto3" json:"day,omitempty"`
	Hour                 int32    `protobuf:"varint,5,opt,name=hour,proto3" json:"hour,omitempty"`
	Minute               int32    `protobuf:"varint,6,opt,name=minute,proto3" json:"minute,omitempty"`
	Second               int32    `protobuf:"varint,7,opt,name=second,proto3" json:"second,omitempty"`
	Timezone             int32    `protobuf:"varint,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerTime) Reset()         { *m = ServerTime{} }
func (m *ServerTime) String() string { return proto.CompactTextString(m) }
func (*ServerTime) ProtoMessage()    {}
func (*ServerTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *ServerTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerTime.Unmarshal(m, b)
}
func (m *ServerTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerTime.Marshal(b, m, deterministic)
}
func (m *ServerTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerTime.Merge(m, src)
}
func (m *ServerTime) XXX_Size() int {
	return xxx_messageInfo_ServerTime.Size(m)
}
func (m *ServerTime) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerTime.DiscardUnknown(m)
}

var xxx_messageInfo_ServerTime proto.InternalMessageInfo

func (m *ServerTime) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ServerTime) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *ServerTime) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *ServerTime) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *ServerTime) GetHour() int32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func (m *ServerTime) GetMinute() int32 {
	if m != nil {
		return m.Minute
	}
	return 0
}

func (m *ServerTime) GetSecond() int32 {
	if m != nil {
		return m.Second
	}
	return 0
}

func (m *ServerTime) GetTimezone() int32 {
	if m != nil {
		return m.Timezone
	}
	return 0
}

type GameItem struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	ObtainTime           int64    `protobuf:"varint,4,opt,name=obtainTime,proto3" json:"obtainTime,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameItem) Reset()         { *m = GameItem{} }
func (m *GameItem) String() string { return proto.CompactTextString(m) }
func (*GameItem) ProtoMessage()    {}
func (*GameItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *GameItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameItem.Unmarshal(m, b)
}
func (m *GameItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameItem.Marshal(b, m, deterministic)
}
func (m *GameItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameItem.Merge(m, src)
}
func (m *GameItem) XXX_Size() int {
	return xxx_messageInfo_GameItem.Size(m)
}
func (m *GameItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GameItem.DiscardUnknown(m)
}

var xxx_messageInfo_GameItem proto.InternalMessageInfo

func (m *GameItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GameItem) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GameItem) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GameItem) GetObtainTime() int64 {
	if m != nil {
		return m.ObtainTime
	}
	return 0
}

func (m *GameItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//时间记录
type TimeRecord struct {
	LastSign             int64    `protobuf:"varint,3,opt,name=lastSign,proto3" json:"lastSign,omitempty"`
	LastGetPVPResult     int64    `protobuf:"varint,6,opt,name=lastGetPVPResult,proto3" json:"lastGetPVPResult,omitempty"`
	LastWeekRec          int64    `protobuf:"varint,7,opt,name=lastWeekRec,proto3" json:"lastWeekRec,omitempty"`
	TotalTime            int32    `protobuf:"varint,8,opt,name=totalTime,proto3" json:"totalTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeRecord) Reset()         { *m = TimeRecord{} }
func (m *TimeRecord) String() string { return proto.CompactTextString(m) }
func (*TimeRecord) ProtoMessage()    {}
func (*TimeRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *TimeRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRecord.Unmarshal(m, b)
}
func (m *TimeRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRecord.Marshal(b, m, deterministic)
}
func (m *TimeRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRecord.Merge(m, src)
}
func (m *TimeRecord) XXX_Size() int {
	return xxx_messageInfo_TimeRecord.Size(m)
}
func (m *TimeRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRecord.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRecord proto.InternalMessageInfo

func (m *TimeRecord) GetLastSign() int64 {
	if m != nil {
		return m.LastSign
	}
	return 0
}

func (m *TimeRecord) GetLastGetPVPResult() int64 {
	if m != nil {
		return m.LastGetPVPResult
	}
	return 0
}

func (m *TimeRecord) GetLastWeekRec() int64 {
	if m != nil {
		return m.LastWeekRec
	}
	return 0
}

func (m *TimeRecord) GetTotalTime() int32 {
	if m != nil {
		return m.TotalTime
	}
	return 0
}

//次数记录
type NumberRecord struct {
	Elo                  int32    `protobuf:"varint,1,opt,name=elo,proto3" json:"elo,omitempty"`
	NormWin              int32    `protobuf:"varint,2,opt,name=normWin,proto3" json:"normWin,omitempty"`
	TotalSignIn          int32    `protobuf:"varint,3,opt,name=totalSignIn,proto3" json:"totalSignIn,omitempty"`
	WeekTotalSign        int32    `protobuf:"varint,4,opt,name=weekTotalSign,proto3" json:"weekTotalSign,omitempty"`
	WeekGoldGet          int32    `protobuf:"varint,5,opt,name=weekGoldGet,proto3" json:"weekGoldGet,omitempty"`
	WeekExpGet           int32    `protobuf:"varint,6,opt,name=weekExpGet,proto3" json:"weekExpGet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumberRecord) Reset()         { *m = NumberRecord{} }
func (m *NumberRecord) String() string { return proto.CompactTextString(m) }
func (*NumberRecord) ProtoMessage()    {}
func (*NumberRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *NumberRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumberRecord.Unmarshal(m, b)
}
func (m *NumberRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumberRecord.Marshal(b, m, deterministic)
}
func (m *NumberRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumberRecord.Merge(m, src)
}
func (m *NumberRecord) XXX_Size() int {
	return xxx_messageInfo_NumberRecord.Size(m)
}
func (m *NumberRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_NumberRecord.DiscardUnknown(m)
}

var xxx_messageInfo_NumberRecord proto.InternalMessageInfo

func (m *NumberRecord) GetElo() int32 {
	if m != nil {
		return m.Elo
	}
	return 0
}

func (m *NumberRecord) GetNormWin() int32 {
	if m != nil {
		return m.NormWin
	}
	return 0
}

func (m *NumberRecord) GetTotalSignIn() int32 {
	if m != nil {
		return m.TotalSignIn
	}
	return 0
}

func (m *NumberRecord) GetWeekTotalSign() int32 {
	if m != nil {
		return m.WeekTotalSign
	}
	return 0
}

func (m *NumberRecord) GetWeekGoldGet() int32 {
	if m != nil {
		return m.WeekGoldGet
	}
	return 0
}

func (m *NumberRecord) GetWeekExpGet() int32 {
	if m != nil {
		return m.WeekExpGet
	}
	return 0
}

type WXInfo struct {
	AvatarUrl            string   `protobuf:"bytes,1,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	OpenId               string   `protobuf:"bytes,4,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	NickName             string   `protobuf:"bytes,6,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Province             string   `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`
	UnionId              string   `protobuf:"bytes,8,opt,name=union_id,json=unionId,proto3" json:"union_id,omitempty"`
	Country              string   `protobuf:"bytes,9,opt,name=country,proto3" json:"country,omitempty"`
	SessionId            string   `protobuf:"bytes,10,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sign                 string   `protobuf:"bytes,11,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WXInfo) Reset()         { *m = WXInfo{} }
func (m *WXInfo) String() string { return proto.CompactTextString(m) }
func (*WXInfo) ProtoMessage()    {}
func (*WXInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *WXInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WXInfo.Unmarshal(m, b)
}
func (m *WXInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WXInfo.Marshal(b, m, deterministic)
}
func (m *WXInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WXInfo.Merge(m, src)
}
func (m *WXInfo) XXX_Size() int {
	return xxx_messageInfo_WXInfo.Size(m)
}
func (m *WXInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WXInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WXInfo proto.InternalMessageInfo

func (m *WXInfo) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *WXInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *WXInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *WXInfo) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *WXInfo) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *WXInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *WXInfo) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *WXInfo) GetUnionId() string {
	if m != nil {
		return m.UnionId
	}
	return ""
}

func (m *WXInfo) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *WXInfo) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *WXInfo) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

//玩家主信息
type GamerMain struct {
	Id                   int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  string      `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Lsid                 int32       `protobuf:"varint,3,opt,name=lsid,proto3" json:"lsid,omitempty"`
	Psid                 int32       `protobuf:"varint,4,opt,name=psid,proto3" json:"psid,omitempty"`
	State                GamerStatus `protobuf:"varint,5,opt,name=state,proto3,enum=GamerStatus" json:"state,omitempty"`
	Name                 string      `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Level                int32       `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	Session              string      `protobuf:"bytes,8,opt,name=session,proto3" json:"session,omitempty"`
	Create               int64       `protobuf:"varint,9,opt,name=create,proto3" json:"create,omitempty"`
	LastLogin            int64       `protobuf:"varint,10,opt,name=lastLogin,proto3" json:"lastLogin,omitempty"`
	LastLogout           int64       `protobuf:"varint,11,opt,name=lastLogout,proto3" json:"lastLogout,omitempty"`
	TypeId               int32       `protobuf:"varint,12,opt,name=typeId,proto3" json:"typeId,omitempty"`
	Icon                 int32       `protobuf:"varint,13,opt,name=icon,proto3" json:"icon,omitempty"`
	Exp                  int32       `protobuf:"varint,14,opt,name=exp,proto3" json:"exp,omitempty"`
	PvpSession           string      `protobuf:"bytes,15,opt,name=pvpSession,proto3" json:"pvpSession,omitempty"`
	Avatar               string      `protobuf:"bytes,16,opt,name=avatar,proto3" json:"avatar,omitempty"`
	LeagueId             int32       `protobuf:"varint,17,opt,name=leagueId,proto3" json:"leagueId,omitempty"`
	IsNewbie             bool        `protobuf:"varint,18,opt,name=isNewbie,proto3" json:"isNewbie,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GamerMain) Reset()         { *m = GamerMain{} }
func (m *GamerMain) String() string { return proto.CompactTextString(m) }
func (*GamerMain) ProtoMessage()    {}
func (*GamerMain) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *GamerMain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerMain.Unmarshal(m, b)
}
func (m *GamerMain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerMain.Marshal(b, m, deterministic)
}
func (m *GamerMain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerMain.Merge(m, src)
}
func (m *GamerMain) XXX_Size() int {
	return xxx_messageInfo_GamerMain.Size(m)
}
func (m *GamerMain) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerMain.DiscardUnknown(m)
}

var xxx_messageInfo_GamerMain proto.InternalMessageInfo

func (m *GamerMain) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GamerMain) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GamerMain) GetLsid() int32 {
	if m != nil {
		return m.Lsid
	}
	return 0
}

func (m *GamerMain) GetPsid() int32 {
	if m != nil {
		return m.Psid
	}
	return 0
}

func (m *GamerMain) GetState() GamerStatus {
	if m != nil {
		return m.State
	}
	return GamerStatus_Offline
}

func (m *GamerMain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GamerMain) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *GamerMain) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *GamerMain) GetCreate() int64 {
	if m != nil {
		return m.Create
	}
	return 0
}

func (m *GamerMain) GetLastLogin() int64 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

func (m *GamerMain) GetLastLogout() int64 {
	if m != nil {
		return m.LastLogout
	}
	return 0
}

func (m *GamerMain) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *GamerMain) GetIcon() int32 {
	if m != nil {
		return m.Icon
	}
	return 0
}

func (m *GamerMain) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *GamerMain) GetPvpSession() string {
	if m != nil {
		return m.PvpSession
	}
	return ""
}

func (m *GamerMain) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *GamerMain) GetLeagueId() int32 {
	if m != nil {
		return m.LeagueId
	}
	return 0
}

func (m *GamerMain) GetIsNewbie() bool {
	if m != nil {
		return m.IsNewbie
	}
	return false
}

type GamerMini struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Lsid                 int32    `protobuf:"varint,4,opt,name=lsid,proto3" json:"lsid,omitempty"`
	Avatar               string   `protobuf:"bytes,16,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamerMini) Reset()         { *m = GamerMini{} }
func (m *GamerMini) String() string { return proto.CompactTextString(m) }
func (*GamerMini) ProtoMessage()    {}
func (*GamerMini) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

func (m *GamerMini) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerMini.Unmarshal(m, b)
}
func (m *GamerMini) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerMini.Marshal(b, m, deterministic)
}
func (m *GamerMini) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerMini.Merge(m, src)
}
func (m *GamerMini) XXX_Size() int {
	return xxx_messageInfo_GamerMini.Size(m)
}
func (m *GamerMini) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerMini.DiscardUnknown(m)
}

var xxx_messageInfo_GamerMini proto.InternalMessageInfo

func (m *GamerMini) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GamerMini) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GamerMini) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *GamerMini) GetLsid() int32 {
	if m != nil {
		return m.Lsid
	}
	return 0
}

func (m *GamerMini) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

//好友请求
type GamerFriendRequest struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Time                 int64      `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	GamerInfo            *GamerMini `protobuf:"bytes,5,opt,name=gamerInfo,proto3" json:"gamerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GamerFriendRequest) Reset()         { *m = GamerFriendRequest{} }
func (m *GamerFriendRequest) String() string { return proto.CompactTextString(m) }
func (*GamerFriendRequest) ProtoMessage()    {}
func (*GamerFriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{7}
}

func (m *GamerFriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerFriendRequest.Unmarshal(m, b)
}
func (m *GamerFriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerFriendRequest.Marshal(b, m, deterministic)
}
func (m *GamerFriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerFriendRequest.Merge(m, src)
}
func (m *GamerFriendRequest) XXX_Size() int {
	return xxx_messageInfo_GamerFriendRequest.Size(m)
}
func (m *GamerFriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerFriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GamerFriendRequest proto.InternalMessageInfo

func (m *GamerFriendRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GamerFriendRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GamerFriendRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *GamerFriendRequest) GetGamerInfo() *GamerMini {
	if m != nil {
		return m.GamerInfo
	}
	return nil
}

//拉黑的玩家
type GamerBlack struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamerBlack) Reset()         { *m = GamerBlack{} }
func (m *GamerBlack) String() string { return proto.CompactTextString(m) }
func (*GamerBlack) ProtoMessage()    {}
func (*GamerBlack) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{8}
}

func (m *GamerBlack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerBlack.Unmarshal(m, b)
}
func (m *GamerBlack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerBlack.Marshal(b, m, deterministic)
}
func (m *GamerBlack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerBlack.Merge(m, src)
}
func (m *GamerBlack) XXX_Size() int {
	return xxx_messageInfo_GamerBlack.Size(m)
}
func (m *GamerBlack) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerBlack.DiscardUnknown(m)
}

var xxx_messageInfo_GamerBlack proto.InternalMessageInfo

func (m *GamerBlack) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GamerFriend struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time                 int64      `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	GamerInfo            *GamerMini `protobuf:"bytes,5,opt,name=gamerInfo,proto3" json:"gamerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GamerFriend) Reset()         { *m = GamerFriend{} }
func (m *GamerFriend) String() string { return proto.CompactTextString(m) }
func (*GamerFriend) ProtoMessage()    {}
func (*GamerFriend) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{9}
}

func (m *GamerFriend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerFriend.Unmarshal(m, b)
}
func (m *GamerFriend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerFriend.Marshal(b, m, deterministic)
}
func (m *GamerFriend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerFriend.Merge(m, src)
}
func (m *GamerFriend) XXX_Size() int {
	return xxx_messageInfo_GamerFriend.Size(m)
}
func (m *GamerFriend) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerFriend.DiscardUnknown(m)
}

var xxx_messageInfo_GamerFriend proto.InternalMessageInfo

func (m *GamerFriend) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GamerFriend) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *GamerFriend) GetGamerInfo() *GamerMini {
	if m != nil {
		return m.GamerInfo
	}
	return nil
}

type ChatData struct {
	From                 int32      `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Time                 int64      `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Msg                  string     `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Channel              int32      `protobuf:"varint,4,opt,name=channel,proto3" json:"channel,omitempty"`
	GamerInfo            *GamerMini `protobuf:"bytes,5,opt,name=gamerInfo,proto3" json:"gamerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChatData) Reset()         { *m = ChatData{} }
func (m *ChatData) String() string { return proto.CompactTextString(m) }
func (*ChatData) ProtoMessage()    {}
func (*ChatData) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{10}
}

func (m *ChatData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatData.Unmarshal(m, b)
}
func (m *ChatData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatData.Marshal(b, m, deterministic)
}
func (m *ChatData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatData.Merge(m, src)
}
func (m *ChatData) XXX_Size() int {
	return xxx_messageInfo_ChatData.Size(m)
}
func (m *ChatData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatData.DiscardUnknown(m)
}

var xxx_messageInfo_ChatData proto.InternalMessageInfo

func (m *ChatData) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *ChatData) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ChatData) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ChatData) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *ChatData) GetGamerInfo() *GamerMini {
	if m != nil {
		return m.GamerInfo
	}
	return nil
}

//邮件
type Mail struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MailType             MailType    `protobuf:"varint,2,opt,name=mailType,proto3,enum=MailType" json:"mailType,omitempty"`
	Time                 int64       `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Theme                string      `protobuf:"bytes,4,opt,name=theme,proto3" json:"theme,omitempty"`
	Msg                  string      `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	Attachments          []*GameItem `protobuf:"bytes,6,rep,name=attachments,proto3" json:"attachments,omitempty"`
	State                MailState   `protobuf:"varint,7,opt,name=state,proto3,enum=MailState" json:"state,omitempty"`
	ServerId             int32       `protobuf:"varint,9,opt,name=serverId,proto3" json:"serverId,omitempty"`
	SenderId             int32       `protobuf:"varint,10,opt,name=senderId,proto3" json:"senderId,omitempty"`
	Level                int32       `protobuf:"varint,11,opt,name=level,proto3" json:"level,omitempty"`
	EndTime              int64       `protobuf:"varint,12,opt,name=endTime,proto3" json:"endTime,omitempty"`
	IsDel                int32       `protobuf:"varint,13,opt,name=isDel,proto3" json:"isDel,omitempty"`
	CfgId                int32       `protobuf:"varint,14,opt,name=cfgId,proto3" json:"cfgId,omitempty"`
	Save                 bool        `protobuf:"varint,15,opt,name=save,proto3" json:"save,omitempty"`
	GamerInfo            *GamerMini  `protobuf:"bytes,16,opt,name=gamerInfo,proto3" json:"gamerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Mail) Reset()         { *m = Mail{} }
func (m *Mail) String() string { return proto.CompactTextString(m) }
func (*Mail) ProtoMessage()    {}
func (*Mail) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{11}
}

func (m *Mail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mail.Unmarshal(m, b)
}
func (m *Mail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mail.Marshal(b, m, deterministic)
}
func (m *Mail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mail.Merge(m, src)
}
func (m *Mail) XXX_Size() int {
	return xxx_messageInfo_Mail.Size(m)
}
func (m *Mail) XXX_DiscardUnknown() {
	xxx_messageInfo_Mail.DiscardUnknown(m)
}

var xxx_messageInfo_Mail proto.InternalMessageInfo

func (m *Mail) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Mail) GetMailType() MailType {
	if m != nil {
		return m.MailType
	}
	return MailType_ActivityMail
}

func (m *Mail) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Mail) GetTheme() string {
	if m != nil {
		return m.Theme
	}
	return ""
}

func (m *Mail) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Mail) GetAttachments() []*GameItem {
	if m != nil {
		return m.Attachments
	}
	return nil
}

func (m *Mail) GetState() MailState {
	if m != nil {
		return m.State
	}
	return MailState_MailUnRead
}

func (m *Mail) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *Mail) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Mail) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Mail) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Mail) GetIsDel() int32 {
	if m != nil {
		return m.IsDel
	}
	return 0
}

func (m *Mail) GetCfgId() int32 {
	if m != nil {
		return m.CfgId
	}
	return 0
}

func (m *Mail) GetSave() bool {
	if m != nil {
		return m.Save
	}
	return false
}

func (m *Mail) GetGamerInfo() *GamerMini {
	if m != nil {
		return m.GamerInfo
	}
	return nil
}

type GamerMatch struct {
	Mini                 *GamerMini `protobuf:"bytes,1,opt,name=mini,proto3" json:"mini,omitempty"`
	Ai                   bool       `protobuf:"varint,2,opt,name=ai,proto3" json:"ai,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GamerMatch) Reset()         { *m = GamerMatch{} }
func (m *GamerMatch) String() string { return proto.CompactTextString(m) }
func (*GamerMatch) ProtoMessage()    {}
func (*GamerMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{12}
}

func (m *GamerMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerMatch.Unmarshal(m, b)
}
func (m *GamerMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerMatch.Marshal(b, m, deterministic)
}
func (m *GamerMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerMatch.Merge(m, src)
}
func (m *GamerMatch) XXX_Size() int {
	return xxx_messageInfo_GamerMatch.Size(m)
}
func (m *GamerMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerMatch.DiscardUnknown(m)
}

var xxx_messageInfo_GamerMatch proto.InternalMessageInfo

func (m *GamerMatch) GetMini() *GamerMini {
	if m != nil {
		return m.Mini
	}
	return nil
}

func (m *GamerMatch) GetAi() bool {
	if m != nil {
		return m.Ai
	}
	return false
}

type MatchInfo struct {
	Session              string        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Time                 int64         `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Addr                 string        `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	FrameDelta           int32         `protobuf:"varint,4,opt,name=frameDelta,proto3" json:"frameDelta,omitempty"`
	MinFrameDelta        int32         `protobuf:"varint,5,opt,name=minFrameDelta,proto3" json:"minFrameDelta,omitempty"`
	MatchTime            int32         `protobuf:"varint,6,opt,name=matchTime,proto3" json:"matchTime,omitempty"`
	InputDelta           int32         `protobuf:"varint,7,opt,name=inputDelta,proto3" json:"inputDelta,omitempty"`
	PvpType              int32         `protobuf:"varint,8,opt,name=pvpType,proto3" json:"pvpType,omitempty"`
	ThreadRecv           bool          `protobuf:"varint,9,opt,name=threadRecv,proto3" json:"threadRecv,omitempty"`
	Gamers               []*GamerMatch `protobuf:"bytes,100,rep,name=gamers,proto3" json:"gamers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MatchInfo) Reset()         { *m = MatchInfo{} }
func (m *MatchInfo) String() string { return proto.CompactTextString(m) }
func (*MatchInfo) ProtoMessage()    {}
func (*MatchInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{13}
}

func (m *MatchInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchInfo.Unmarshal(m, b)
}
func (m *MatchInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchInfo.Marshal(b, m, deterministic)
}
func (m *MatchInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchInfo.Merge(m, src)
}
func (m *MatchInfo) XXX_Size() int {
	return xxx_messageInfo_MatchInfo.Size(m)
}
func (m *MatchInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MatchInfo proto.InternalMessageInfo

func (m *MatchInfo) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *MatchInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *MatchInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *MatchInfo) GetFrameDelta() int32 {
	if m != nil {
		return m.FrameDelta
	}
	return 0
}

func (m *MatchInfo) GetMinFrameDelta() int32 {
	if m != nil {
		return m.MinFrameDelta
	}
	return 0
}

func (m *MatchInfo) GetMatchTime() int32 {
	if m != nil {
		return m.MatchTime
	}
	return 0
}

func (m *MatchInfo) GetInputDelta() int32 {
	if m != nil {
		return m.InputDelta
	}
	return 0
}

func (m *MatchInfo) GetPvpType() int32 {
	if m != nil {
		return m.PvpType
	}
	return 0
}

func (m *MatchInfo) GetThreadRecv() bool {
	if m != nil {
		return m.ThreadRecv
	}
	return false
}

func (m *MatchInfo) GetGamers() []*GamerMatch {
	if m != nil {
		return m.Gamers
	}
	return nil
}

type PVPInput struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Yaw                  int32    `protobuf:"varint,2,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Btn                  int32    `protobuf:"varint,3,opt,name=btn,proto3" json:"btn,omitempty"`
	Pos                  int32    `protobuf:"varint,4,opt,name=pos,proto3" json:"pos,omitempty"`
	Talk                 int32    `protobuf:"varint,5,opt,name=talk,proto3" json:"talk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PVPInput) Reset()         { *m = PVPInput{} }
func (m *PVPInput) String() string { return proto.CompactTextString(m) }
func (*PVPInput) ProtoMessage()    {}
func (*PVPInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{14}
}

func (m *PVPInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPInput.Unmarshal(m, b)
}
func (m *PVPInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPInput.Marshal(b, m, deterministic)
}
func (m *PVPInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPInput.Merge(m, src)
}
func (m *PVPInput) XXX_Size() int {
	return xxx_messageInfo_PVPInput.Size(m)
}
func (m *PVPInput) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPInput.DiscardUnknown(m)
}

var xxx_messageInfo_PVPInput proto.InternalMessageInfo

func (m *PVPInput) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PVPInput) GetYaw() int32 {
	if m != nil {
		return m.Yaw
	}
	return 0
}

func (m *PVPInput) GetBtn() int32 {
	if m != nil {
		return m.Btn
	}
	return 0
}

func (m *PVPInput) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *PVPInput) GetTalk() int32 {
	if m != nil {
		return m.Talk
	}
	return 0
}

type PVPFrame struct {
	Delta                int32       `protobuf:"varint,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Frame                int32       `protobuf:"varint,2,opt,name=frame,proto3" json:"frame,omitempty"`
	End                  bool        `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	Inputs               []*PVPInput `protobuf:"bytes,100,rep,name=inputs,proto3" json:"inputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PVPFrame) Reset()         { *m = PVPFrame{} }
func (m *PVPFrame) String() string { return proto.CompactTextString(m) }
func (*PVPFrame) ProtoMessage()    {}
func (*PVPFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{15}
}

func (m *PVPFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPFrame.Unmarshal(m, b)
}
func (m *PVPFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPFrame.Marshal(b, m, deterministic)
}
func (m *PVPFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPFrame.Merge(m, src)
}
func (m *PVPFrame) XXX_Size() int {
	return xxx_messageInfo_PVPFrame.Size(m)
}
func (m *PVPFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPFrame.DiscardUnknown(m)
}

var xxx_messageInfo_PVPFrame proto.InternalMessageInfo

func (m *PVPFrame) GetDelta() int32 {
	if m != nil {
		return m.Delta
	}
	return 0
}

func (m *PVPFrame) GetFrame() int32 {
	if m != nil {
		return m.Frame
	}
	return 0
}

func (m *PVPFrame) GetEnd() bool {
	if m != nil {
		return m.End
	}
	return false
}

func (m *PVPFrame) GetInputs() []*PVPInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

type PVPFrames struct {
	Frames               []*PVPFrame `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PVPFrames) Reset()         { *m = PVPFrames{} }
func (m *PVPFrames) String() string { return proto.CompactTextString(m) }
func (*PVPFrames) ProtoMessage()    {}
func (*PVPFrames) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{16}
}

func (m *PVPFrames) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPFrames.Unmarshal(m, b)
}
func (m *PVPFrames) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPFrames.Marshal(b, m, deterministic)
}
func (m *PVPFrames) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPFrames.Merge(m, src)
}
func (m *PVPFrames) XXX_Size() int {
	return xxx_messageInfo_PVPFrames.Size(m)
}
func (m *PVPFrames) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPFrames.DiscardUnknown(m)
}

var xxx_messageInfo_PVPFrames proto.InternalMessageInfo

func (m *PVPFrames) GetFrames() []*PVPFrame {
	if m != nil {
		return m.Frames
	}
	return nil
}

type PVPResult struct {
	Kills                []int32     `protobuf:"varint,1,rep,packed,name=kills,proto3" json:"kills,omitempty"`
	Length               []int32     `protobuf:"varint,2,rep,packed,name=length,proto3" json:"length,omitempty"`
	Time                 int64       `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Gone                 []int32     `protobuf:"varint,4,rep,packed,name=gone,proto3" json:"gone,omitempty"`
	Version              int32       `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	MatchInfo            *MatchInfo  `protobuf:"bytes,101,opt,name=matchInfo,proto3" json:"matchInfo,omitempty"`
	Frames               []*PVPFrame `protobuf:"bytes,102,rep,name=frames,proto3" json:"frames,omitempty"`
	Md5                  string      `protobuf:"bytes,103,opt,name=md5,proto3" json:"md5,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PVPResult) Reset()         { *m = PVPResult{} }
func (m *PVPResult) String() string { return proto.CompactTextString(m) }
func (*PVPResult) ProtoMessage()    {}
func (*PVPResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{17}
}

func (m *PVPResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPResult.Unmarshal(m, b)
}
func (m *PVPResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPResult.Marshal(b, m, deterministic)
}
func (m *PVPResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPResult.Merge(m, src)
}
func (m *PVPResult) XXX_Size() int {
	return xxx_messageInfo_PVPResult.Size(m)
}
func (m *PVPResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPResult.DiscardUnknown(m)
}

var xxx_messageInfo_PVPResult proto.InternalMessageInfo

func (m *PVPResult) GetKills() []int32 {
	if m != nil {
		return m.Kills
	}
	return nil
}

func (m *PVPResult) GetLength() []int32 {
	if m != nil {
		return m.Length
	}
	return nil
}

func (m *PVPResult) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PVPResult) GetGone() []int32 {
	if m != nil {
		return m.Gone
	}
	return nil
}

func (m *PVPResult) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PVPResult) GetMatchInfo() *MatchInfo {
	if m != nil {
		return m.MatchInfo
	}
	return nil
}

func (m *PVPResult) GetFrames() []*PVPFrame {
	if m != nil {
		return m.Frames
	}
	return nil
}

func (m *PVPResult) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

type RankLength struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Length               int32      `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Rank                 int32      `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	Mini                 *GamerMini `protobuf:"bytes,4,opt,name=mini,proto3" json:"mini,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RankLength) Reset()         { *m = RankLength{} }
func (m *RankLength) String() string { return proto.CompactTextString(m) }
func (*RankLength) ProtoMessage()    {}
func (*RankLength) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{18}
}

func (m *RankLength) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankLength.Unmarshal(m, b)
}
func (m *RankLength) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankLength.Marshal(b, m, deterministic)
}
func (m *RankLength) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankLength.Merge(m, src)
}
func (m *RankLength) XXX_Size() int {
	return xxx_messageInfo_RankLength.Size(m)
}
func (m *RankLength) XXX_DiscardUnknown() {
	xxx_messageInfo_RankLength.DiscardUnknown(m)
}

var xxx_messageInfo_RankLength proto.InternalMessageInfo

func (m *RankLength) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RankLength) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *RankLength) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *RankLength) GetMini() *GamerMini {
	if m != nil {
		return m.Mini
	}
	return nil
}

//艺人
type Actor struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Star                 int32    `protobuf:"varint,4,opt,name=star,proto3" json:"star,omitempty"`
	Exp                  int32    `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	BulidId              int32    `protobuf:"varint,6,opt,name=bulidId,proto3" json:"bulidId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Actor) Reset()         { *m = Actor{} }
func (m *Actor) String() string { return proto.CompactTextString(m) }
func (*Actor) ProtoMessage()    {}
func (*Actor) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{19}
}

func (m *Actor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Actor.Unmarshal(m, b)
}
func (m *Actor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Actor.Marshal(b, m, deterministic)
}
func (m *Actor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actor.Merge(m, src)
}
func (m *Actor) XXX_Size() int {
	return xxx_messageInfo_Actor.Size(m)
}
func (m *Actor) XXX_DiscardUnknown() {
	xxx_messageInfo_Actor.DiscardUnknown(m)
}

var xxx_messageInfo_Actor proto.InternalMessageInfo

func (m *Actor) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Actor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Actor) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Actor) GetStar() int32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *Actor) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *Actor) GetBulidId() int32 {
	if m != nil {
		return m.BulidId
	}
	return 0
}

//建筑信息
type BuildInfo struct {
	BuildId              int32             `protobuf:"varint,1,opt,name=buildId,proto3" json:"buildId,omitempty"`
	BuildType            int32             `protobuf:"varint,2,opt,name=buildType,proto3" json:"buildType,omitempty"`
	BuildLevel           int32             `protobuf:"varint,3,opt,name=buildLevel,proto3" json:"buildLevel,omitempty"`
	EndTime              int64             `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	State                BuildState        `protobuf:"varint,5,opt,name=state,proto3,enum=BuildState" json:"state,omitempty"`
	BreakLevelMax        int32             `protobuf:"varint,6,opt,name=breakLevelMax,proto3" json:"breakLevelMax,omitempty"`
	ProductInfo          *BuildProduct     `protobuf:"bytes,7,opt,name=productInfo,proto3" json:"productInfo,omitempty"`
	ActorCell            []*BuildActorCell `protobuf:"bytes,8,rep,name=actorCell,proto3" json:"actorCell,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BuildInfo) Reset()         { *m = BuildInfo{} }
func (m *BuildInfo) String() string { return proto.CompactTextString(m) }
func (*BuildInfo) ProtoMessage()    {}
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{20}
}

func (m *BuildInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildInfo.Unmarshal(m, b)
}
func (m *BuildInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildInfo.Marshal(b, m, deterministic)
}
func (m *BuildInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildInfo.Merge(m, src)
}
func (m *BuildInfo) XXX_Size() int {
	return xxx_messageInfo_BuildInfo.Size(m)
}
func (m *BuildInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BuildInfo proto.InternalMessageInfo

func (m *BuildInfo) GetBuildId() int32 {
	if m != nil {
		return m.BuildId
	}
	return 0
}

func (m *BuildInfo) GetBuildType() int32 {
	if m != nil {
		return m.BuildType
	}
	return 0
}

func (m *BuildInfo) GetBuildLevel() int32 {
	if m != nil {
		return m.BuildLevel
	}
	return 0
}

func (m *BuildInfo) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *BuildInfo) GetState() BuildState {
	if m != nil {
		return m.State
	}
	return BuildState_Normal
}

func (m *BuildInfo) GetBreakLevelMax() int32 {
	if m != nil {
		return m.BreakLevelMax
	}
	return 0
}

func (m *BuildInfo) GetProductInfo() *BuildProduct {
	if m != nil {
		return m.ProductInfo
	}
	return nil
}

func (m *BuildInfo) GetActorCell() []*BuildActorCell {
	if m != nil {
		return m.ActorCell
	}
	return nil
}

type BuildProduct struct {
	StartTime            int64    `protobuf:"varint,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	NotGetNum            int32    `protobuf:"varint,2,opt,name=notGetNum,proto3" json:"notGetNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildProduct) Reset()         { *m = BuildProduct{} }
func (m *BuildProduct) String() string { return proto.CompactTextString(m) }
func (*BuildProduct) ProtoMessage()    {}
func (*BuildProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{21}
}

func (m *BuildProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildProduct.Unmarshal(m, b)
}
func (m *BuildProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildProduct.Marshal(b, m, deterministic)
}
func (m *BuildProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildProduct.Merge(m, src)
}
func (m *BuildProduct) XXX_Size() int {
	return xxx_messageInfo_BuildProduct.Size(m)
}
func (m *BuildProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildProduct.DiscardUnknown(m)
}

var xxx_messageInfo_BuildProduct proto.InternalMessageInfo

func (m *BuildProduct) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *BuildProduct) GetNotGetNum() int32 {
	if m != nil {
		return m.NotGetNum
	}
	return 0
}

type BuildActorCell struct {
	CellId               int32    `protobuf:"varint,1,opt,name=cellId,proto3" json:"cellId,omitempty"`
	ActorId              int32    `protobuf:"varint,2,opt,name=actorId,proto3" json:"actorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildActorCell) Reset()         { *m = BuildActorCell{} }
func (m *BuildActorCell) String() string { return proto.CompactTextString(m) }
func (*BuildActorCell) ProtoMessage()    {}
func (*BuildActorCell) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{22}
}

func (m *BuildActorCell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildActorCell.Unmarshal(m, b)
}
func (m *BuildActorCell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildActorCell.Marshal(b, m, deterministic)
}
func (m *BuildActorCell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildActorCell.Merge(m, src)
}
func (m *BuildActorCell) XXX_Size() int {
	return xxx_messageInfo_BuildActorCell.Size(m)
}
func (m *BuildActorCell) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildActorCell.DiscardUnknown(m)
}

var xxx_messageInfo_BuildActorCell proto.InternalMessageInfo

func (m *BuildActorCell) GetCellId() int32 {
	if m != nil {
		return m.CellId
	}
	return 0
}

func (m *BuildActorCell) GetActorId() int32 {
	if m != nil {
		return m.ActorId
	}
	return 0
}

//情报
type Intelligence struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	ObtainTime           int64    `protobuf:"varint,3,opt,name=obtainTime,proto3" json:"obtainTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Intelligence) Reset()         { *m = Intelligence{} }
func (m *Intelligence) String() string { return proto.CompactTextString(m) }
func (*Intelligence) ProtoMessage()    {}
func (*Intelligence) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{23}
}

func (m *Intelligence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Intelligence.Unmarshal(m, b)
}
func (m *Intelligence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Intelligence.Marshal(b, m, deterministic)
}
func (m *Intelligence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Intelligence.Merge(m, src)
}
func (m *Intelligence) XXX_Size() int {
	return xxx_messageInfo_Intelligence.Size(m)
}
func (m *Intelligence) XXX_DiscardUnknown() {
	xxx_messageInfo_Intelligence.DiscardUnknown(m)
}

var xxx_messageInfo_Intelligence proto.InternalMessageInfo

func (m *Intelligence) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Intelligence) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Intelligence) GetObtainTime() int64 {
	if m != nil {
		return m.ObtainTime
	}
	return 0
}

// 拍摄--剧本
type StudioStory struct {
	StoryType            StudioStoryType `protobuf:"varint,1,opt,name=storyType,proto3,enum=StudioStoryType" json:"storyType,omitempty"`
	StoryId              int32           `protobuf:"varint,2,opt,name=storyId,proto3" json:"storyId,omitempty"`
	StoryName            string          `protobuf:"bytes,3,opt,name=storyName,proto3" json:"storyName,omitempty"`
	Expect               int32           `protobuf:"varint,4,opt,name=expect,proto3" json:"expect,omitempty"`
	EventNum             int32           `protobuf:"varint,5,opt,name=eventNum,proto3" json:"eventNum,omitempty"`
	Season               int32           `protobuf:"varint,6,opt,name=season,proto3" json:"season,omitempty"`
	Episode              int32           `protobuf:"varint,7,opt,name=episode,proto3" json:"episode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StudioStory) Reset()         { *m = StudioStory{} }
func (m *StudioStory) String() string { return proto.CompactTextString(m) }
func (*StudioStory) ProtoMessage()    {}
func (*StudioStory) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{24}
}

func (m *StudioStory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudioStory.Unmarshal(m, b)
}
func (m *StudioStory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudioStory.Marshal(b, m, deterministic)
}
func (m *StudioStory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudioStory.Merge(m, src)
}
func (m *StudioStory) XXX_Size() int {
	return xxx_messageInfo_StudioStory.Size(m)
}
func (m *StudioStory) XXX_DiscardUnknown() {
	xxx_messageInfo_StudioStory.DiscardUnknown(m)
}

var xxx_messageInfo_StudioStory proto.InternalMessageInfo

func (m *StudioStory) GetStoryType() StudioStoryType {
	if m != nil {
		return m.StoryType
	}
	return StudioStoryType_StudioStoryType_Normal
}

func (m *StudioStory) GetStoryId() int32 {
	if m != nil {
		return m.StoryId
	}
	return 0
}

func (m *StudioStory) GetStoryName() string {
	if m != nil {
		return m.StoryName
	}
	return ""
}

func (m *StudioStory) GetExpect() int32 {
	if m != nil {
		return m.Expect
	}
	return 0
}

func (m *StudioStory) GetEventNum() int32 {
	if m != nil {
		return m.EventNum
	}
	return 0
}

func (m *StudioStory) GetSeason() int32 {
	if m != nil {
		return m.Season
	}
	return 0
}

func (m *StudioStory) GetEpisode() int32 {
	if m != nil {
		return m.Episode
	}
	return 0
}

// 拍摄--艺人
type StudioActor struct {
	StoryCharactersId    int32               `protobuf:"varint,1,opt,name=storyCharactersId,proto3" json:"storyCharactersId,omitempty"`
	ActorId              int32               `protobuf:"varint,2,opt,name=actorId,proto3" json:"actorId,omitempty"`
	Cost                 int32               `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	ActorState           StudioActorState    `protobuf:"varint,4,opt,name=actorState,proto3,enum=StudioActorState" json:"actorState,omitempty"`
	IsMvp                bool                `protobuf:"varint,5,opt,name=isMvp,proto3" json:"isMvp,omitempty"`
	MatchingLabels       []int32             `protobuf:"varint,6,rep,packed,name=matchingLabels,proto3" json:"matchingLabels,omitempty"`
	MatchingProps        []*StudioActorProp  `protobuf:"bytes,7,rep,name=matchingProps,proto3" json:"matchingProps,omitempty"`
	ScoreProps           []*StudioActorProp  `protobuf:"bytes,8,rep,name=scoreProps,proto3" json:"scoreProps,omitempty"`
	Skills               []*StudioActorSkill `protobuf:"bytes,9,rep,name=skills,proto3" json:"skills,omitempty"`
	NormalScoreTotal     int32               `protobuf:"varint,10,opt,name=normalScoreTotal,proto3" json:"normalScoreTotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *StudioActor) Reset()         { *m = StudioActor{} }
func (m *StudioActor) String() string { return proto.CompactTextString(m) }
func (*StudioActor) ProtoMessage()    {}
func (*StudioActor) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{25}
}

func (m *StudioActor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudioActor.Unmarshal(m, b)
}
func (m *StudioActor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudioActor.Marshal(b, m, deterministic)
}
func (m *StudioActor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudioActor.Merge(m, src)
}
func (m *StudioActor) XXX_Size() int {
	return xxx_messageInfo_StudioActor.Size(m)
}
func (m *StudioActor) XXX_DiscardUnknown() {
	xxx_messageInfo_StudioActor.DiscardUnknown(m)
}

var xxx_messageInfo_StudioActor proto.InternalMessageInfo

func (m *StudioActor) GetStoryCharactersId() int32 {
	if m != nil {
		return m.StoryCharactersId
	}
	return 0
}

func (m *StudioActor) GetActorId() int32 {
	if m != nil {
		return m.ActorId
	}
	return 0
}

func (m *StudioActor) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *StudioActor) GetActorState() StudioActorState {
	if m != nil {
		return m.ActorState
	}
	return StudioActorState_normal
}

func (m *StudioActor) GetIsMvp() bool {
	if m != nil {
		return m.IsMvp
	}
	return false
}

func (m *StudioActor) GetMatchingLabels() []int32 {
	if m != nil {
		return m.MatchingLabels
	}
	return nil
}

func (m *StudioActor) GetMatchingProps() []*StudioActorProp {
	if m != nil {
		return m.MatchingProps
	}
	return nil
}

func (m *StudioActor) GetScoreProps() []*StudioActorProp {
	if m != nil {
		return m.ScoreProps
	}
	return nil
}

func (m *StudioActor) GetSkills() []*StudioActorSkill {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *StudioActor) GetNormalScoreTotal() int32 {
	if m != nil {
		return m.NormalScoreTotal
	}
	return 0
}

// 拍摄--艺人--属性
type StudioActorProp struct {
	PropId               int32    `protobuf:"varint,1,opt,name=propId,proto3" json:"propId,omitempty"`
	PropVal              int32    `protobuf:"varint,2,opt,name=propVal,proto3" json:"propVal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudioActorProp) Reset()         { *m = StudioActorProp{} }
func (m *StudioActorProp) String() string { return proto.CompactTextString(m) }
func (*StudioActorProp) ProtoMessage()    {}
func (*StudioActorProp) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{26}
}

func (m *StudioActorProp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudioActorProp.Unmarshal(m, b)
}
func (m *StudioActorProp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudioActorProp.Marshal(b, m, deterministic)
}
func (m *StudioActorProp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudioActorProp.Merge(m, src)
}
func (m *StudioActorProp) XXX_Size() int {
	return xxx_messageInfo_StudioActorProp.Size(m)
}
func (m *StudioActorProp) XXX_DiscardUnknown() {
	xxx_messageInfo_StudioActorProp.DiscardUnknown(m)
}

var xxx_messageInfo_StudioActorProp proto.InternalMessageInfo

func (m *StudioActorProp) GetPropId() int32 {
	if m != nil {
		return m.PropId
	}
	return 0
}

func (m *StudioActorProp) GetPropVal() int32 {
	if m != nil {
		return m.PropVal
	}
	return 0
}

// 拍摄--艺人--技能
type StudioActorSkill struct {
	SkillId              int32    `protobuf:"varint,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
	Score                int32    `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudioActorSkill) Reset()         { *m = StudioActorSkill{} }
func (m *StudioActorSkill) String() string { return proto.CompactTextString(m) }
func (*StudioActorSkill) ProtoMessage()    {}
func (*StudioActorSkill) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{27}
}

func (m *StudioActorSkill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudioActorSkill.Unmarshal(m, b)
}
func (m *StudioActorSkill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudioActorSkill.Marshal(b, m, deterministic)
}
func (m *StudioActorSkill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudioActorSkill.Merge(m, src)
}
func (m *StudioActorSkill) XXX_Size() int {
	return xxx_messageInfo_StudioActorSkill.Size(m)
}
func (m *StudioActorSkill) XXX_DiscardUnknown() {
	xxx_messageInfo_StudioActorSkill.DiscardUnknown(m)
}

var xxx_messageInfo_StudioActorSkill proto.InternalMessageInfo

func (m *StudioActorSkill) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *StudioActorSkill) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

// 拍摄--事件
type StudioEvent struct {
	EventId              int32           `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventType            StudioEventType `protobuf:"varint,2,opt,name=eventType,proto3,enum=StudioEventType" json:"eventType,omitempty"`
	EventOption          int32           `protobuf:"varint,3,opt,name=eventOption,proto3" json:"eventOption,omitempty"`
	EventEvaluations     []int32         `protobuf:"varint,4,rep,packed,name=eventEvaluations,proto3" json:"eventEvaluations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StudioEvent) Reset()         { *m = StudioEvent{} }
func (m *StudioEvent) String() string { return proto.CompactTextString(m) }
func (*StudioEvent) ProtoMessage()    {}
func (*StudioEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{28}
}

func (m *StudioEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudioEvent.Unmarshal(m, b)
}
func (m *StudioEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudioEvent.Marshal(b, m, deterministic)
}
func (m *StudioEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudioEvent.Merge(m, src)
}
func (m *StudioEvent) XXX_Size() int {
	return xxx_messageInfo_StudioEvent.Size(m)
}
func (m *StudioEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_StudioEvent.DiscardUnknown(m)
}

var xxx_messageInfo_StudioEvent proto.InternalMessageInfo

func (m *StudioEvent) GetEventId() int32 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *StudioEvent) GetEventType() StudioEventType {
	if m != nil {
		return m.EventType
	}
	return StudioEventType_storyCharactersBest
}

func (m *StudioEvent) GetEventOption() int32 {
	if m != nil {
		return m.EventOption
	}
	return 0
}

func (m *StudioEvent) GetEventEvaluations() []int32 {
	if m != nil {
		return m.EventEvaluations
	}
	return nil
}

// 拍摄--结算
type StudioResult struct {
	Level                int32       `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Score                int32       `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	FirstProfit          int32       `protobuf:"varint,3,opt,name=firstProfit,proto3" json:"firstProfit,omitempty"`
	FirstReward          []*GameItem `protobuf:"bytes,4,rep,name=firstReward,proto3" json:"firstReward,omitempty"`
	ContinuedProfit      int32       `protobuf:"varint,5,opt,name=continuedProfit,proto3" json:"continuedProfit,omitempty"`
	ContinuedBuyCount    int32       `protobuf:"varint,6,opt,name=continuedBuyCount,proto3" json:"continuedBuyCount,omitempty"`
	AudienceEvaluation   []int32     `protobuf:"varint,7,rep,packed,name=audienceEvaluation,proto3" json:"audienceEvaluation,omitempty"`
	ExpReward            []*GameItem `protobuf:"bytes,8,rep,name=expReward,proto3" json:"expReward,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StudioResult) Reset()         { *m = StudioResult{} }
func (m *StudioResult) String() string { return proto.CompactTextString(m) }
func (*StudioResult) ProtoMessage()    {}
func (*StudioResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{29}
}

func (m *StudioResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudioResult.Unmarshal(m, b)
}
func (m *StudioResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudioResult.Marshal(b, m, deterministic)
}
func (m *StudioResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudioResult.Merge(m, src)
}
func (m *StudioResult) XXX_Size() int {
	return xxx_messageInfo_StudioResult.Size(m)
}
func (m *StudioResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StudioResult.DiscardUnknown(m)
}

var xxx_messageInfo_StudioResult proto.InternalMessageInfo

func (m *StudioResult) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *StudioResult) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *StudioResult) GetFirstProfit() int32 {
	if m != nil {
		return m.FirstProfit
	}
	return 0
}

func (m *StudioResult) GetFirstReward() []*GameItem {
	if m != nil {
		return m.FirstReward
	}
	return nil
}

func (m *StudioResult) GetContinuedProfit() int32 {
	if m != nil {
		return m.ContinuedProfit
	}
	return 0
}

func (m *StudioResult) GetContinuedBuyCount() int32 {
	if m != nil {
		return m.ContinuedBuyCount
	}
	return 0
}

func (m *StudioResult) GetAudienceEvaluation() []int32 {
	if m != nil {
		return m.AudienceEvaluation
	}
	return nil
}

func (m *StudioResult) GetExpReward() []*GameItem {
	if m != nil {
		return m.ExpReward
	}
	return nil
}

//拍摄--数据
type StudioData struct {
	Step                 StudioStep     `protobuf:"varint,1,opt,name=step,proto3,enum=StudioStep" json:"step,omitempty"`
	Story                *StudioStory   `protobuf:"bytes,2,opt,name=story,proto3" json:"story,omitempty"`
	Actors               []*StudioStory `protobuf:"bytes,3,rep,name=actors,proto3" json:"actors,omitempty"`
	Event                *StudioEvent   `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	Result               *StudioResult  `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StudioData) Reset()         { *m = StudioData{} }
func (m *StudioData) String() string { return proto.CompactTextString(m) }
func (*StudioData) ProtoMessage()    {}
func (*StudioData) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{30}
}

func (m *StudioData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudioData.Unmarshal(m, b)
}
func (m *StudioData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudioData.Marshal(b, m, deterministic)
}
func (m *StudioData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudioData.Merge(m, src)
}
func (m *StudioData) XXX_Size() int {
	return xxx_messageInfo_StudioData.Size(m)
}
func (m *StudioData) XXX_DiscardUnknown() {
	xxx_messageInfo_StudioData.DiscardUnknown(m)
}

var xxx_messageInfo_StudioData proto.InternalMessageInfo

func (m *StudioData) GetStep() StudioStep {
	if m != nil {
		return m.Step
	}
	return StudioStep_requestStoryList
}

func (m *StudioData) GetStory() *StudioStory {
	if m != nil {
		return m.Story
	}
	return nil
}

func (m *StudioData) GetActors() []*StudioStory {
	if m != nil {
		return m.Actors
	}
	return nil
}

func (m *StudioData) GetEvent() *StudioEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *StudioData) GetResult() *StudioResult {
	if m != nil {
		return m.Result
	}
	return nil
}

// 拍摄后期收益数据
type StudioContinuedData struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	StoryId              int32    `protobuf:"varint,2,opt,name=storyId,proto3" json:"storyId,omitempty"`
	StoryName            string   `protobuf:"bytes,3,opt,name=storyName,proto3" json:"storyName,omitempty"`
	Season               int32    `protobuf:"varint,4,opt,name=season,proto3" json:"season,omitempty"`
	Episode              int32    `protobuf:"varint,5,opt,name=episode,proto3" json:"episode,omitempty"`
	ProfitList           []int32  `protobuf:"varint,6,rep,packed,name=profitList,proto3" json:"profitList,omitempty"`
	ProfitCurrent        int32    `protobuf:"varint,7,opt,name=profitCurrent,proto3" json:"profitCurrent,omitempty"`
	ProfitTimestamp      int32    `protobuf:"varint,8,opt,name=profitTimestamp,proto3" json:"profitTimestamp,omitempty"`
	ProfitCd             int32    `protobuf:"varint,9,opt,name=profitCd,proto3" json:"profitCd,omitempty"`
	ProfitNum            int32    `protobuf:"varint,10,opt,name=profitNum,proto3" json:"profitNum,omitempty"`
	ProfitEndTimestamp   int32    `protobuf:"varint,11,opt,name=profitEndTimestamp,proto3" json:"profitEndTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudioContinuedData) Reset()         { *m = StudioContinuedData{} }
func (m *StudioContinuedData) String() string { return proto.CompactTextString(m) }
func (*StudioContinuedData) ProtoMessage()    {}
func (*StudioContinuedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{31}
}

func (m *StudioContinuedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudioContinuedData.Unmarshal(m, b)
}
func (m *StudioContinuedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudioContinuedData.Marshal(b, m, deterministic)
}
func (m *StudioContinuedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudioContinuedData.Merge(m, src)
}
func (m *StudioContinuedData) XXX_Size() int {
	return xxx_messageInfo_StudioContinuedData.Size(m)
}
func (m *StudioContinuedData) XXX_DiscardUnknown() {
	xxx_messageInfo_StudioContinuedData.DiscardUnknown(m)
}

var xxx_messageInfo_StudioContinuedData proto.InternalMessageInfo

func (m *StudioContinuedData) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *StudioContinuedData) GetStoryId() int32 {
	if m != nil {
		return m.StoryId
	}
	return 0
}

func (m *StudioContinuedData) GetStoryName() string {
	if m != nil {
		return m.StoryName
	}
	return ""
}

func (m *StudioContinuedData) GetSeason() int32 {
	if m != nil {
		return m.Season
	}
	return 0
}

func (m *StudioContinuedData) GetEpisode() int32 {
	if m != nil {
		return m.Episode
	}
	return 0
}

func (m *StudioContinuedData) GetProfitList() []int32 {
	if m != nil {
		return m.ProfitList
	}
	return nil
}

func (m *StudioContinuedData) GetProfitCurrent() int32 {
	if m != nil {
		return m.ProfitCurrent
	}
	return 0
}

func (m *StudioContinuedData) GetProfitTimestamp() int32 {
	if m != nil {
		return m.ProfitTimestamp
	}
	return 0
}

func (m *StudioContinuedData) GetProfitCd() int32 {
	if m != nil {
		return m.ProfitCd
	}
	return 0
}

func (m *StudioContinuedData) GetProfitNum() int32 {
	if m != nil {
		return m.ProfitNum
	}
	return 0
}

func (m *StudioContinuedData) GetProfitEndTimestamp() int32 {
	if m != nil {
		return m.ProfitEndTimestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*ServerTime)(nil), "ServerTime")
	proto.RegisterType((*GameItem)(nil), "GameItem")
	proto.RegisterType((*TimeRecord)(nil), "TimeRecord")
	proto.RegisterType((*NumberRecord)(nil), "NumberRecord")
	proto.RegisterType((*WXInfo)(nil), "WXInfo")
	proto.RegisterType((*GamerMain)(nil), "GamerMain")
	proto.RegisterType((*GamerMini)(nil), "GamerMini")
	proto.RegisterType((*GamerFriendRequest)(nil), "GamerFriendRequest")
	proto.RegisterType((*GamerBlack)(nil), "GamerBlack")
	proto.RegisterType((*GamerFriend)(nil), "GamerFriend")
	proto.RegisterType((*ChatData)(nil), "ChatData")
	proto.RegisterType((*Mail)(nil), "Mail")
	proto.RegisterType((*GamerMatch)(nil), "GamerMatch")
	proto.RegisterType((*MatchInfo)(nil), "MatchInfo")
	proto.RegisterType((*PVPInput)(nil), "PVPInput")
	proto.RegisterType((*PVPFrame)(nil), "PVPFrame")
	proto.RegisterType((*PVPFrames)(nil), "PVPFrames")
	proto.RegisterType((*PVPResult)(nil), "PVPResult")
	proto.RegisterType((*RankLength)(nil), "RankLength")
	proto.RegisterType((*Actor)(nil), "Actor")
	proto.RegisterType((*BuildInfo)(nil), "BuildInfo")
	proto.RegisterType((*BuildProduct)(nil), "BuildProduct")
	proto.RegisterType((*BuildActorCell)(nil), "BuildActorCell")
	proto.RegisterType((*Intelligence)(nil), "Intelligence")
	proto.RegisterType((*StudioStory)(nil), "StudioStory")
	proto.RegisterType((*StudioActor)(nil), "StudioActor")
	proto.RegisterType((*StudioActorProp)(nil), "StudioActorProp")
	proto.RegisterType((*StudioActorSkill)(nil), "StudioActorSkill")
	proto.RegisterType((*StudioEvent)(nil), "StudioEvent")
	proto.RegisterType((*StudioResult)(nil), "StudioResult")
	proto.RegisterType((*StudioData)(nil), "StudioData")
	proto.RegisterType((*StudioContinuedData)(nil), "StudioContinuedData")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 2228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x4f, 0x6f, 0x24, 0x39,
	0xd9, 0x57, 0x77, 0xa7, 0x3b, 0x5d, 0x4f, 0x67, 0x32, 0x59, 0xbf, 0xa3, 0x97, 0x62, 0x58, 0x96,
	0x6c, 0x31, 0x0b, 0x61, 0x81, 0x06, 0x82, 0x96, 0x13, 0x97, 0x9d, 0xcc, 0xec, 0xa8, 0xd1, 0x64,
	0x88, 0x9c, 0x30, 0x83, 0xc4, 0x61, 0xe4, 0x74, 0x39, 0xdd, 0x56, 0xaa, 0xec, 0xda, 0x2a, 0x57,
	0x4f, 0xc2, 0x8d, 0x1b, 0x1f, 0x80, 0x13, 0x9c, 0x41, 0xe2, 0xc6, 0x99, 0x1b, 0x08, 0xf1, 0x21,
	0xe0, 0x23, 0xf0, 0x25, 0xd0, 0xf3, 0xd8, 0xae, 0xaa, 0xee, 0x74, 0x90, 0x56, 0x7b, 0xf3, 0xef,
	0xf7, 0xb8, 0xec, 0xe7, 0xbf, 0xed, 0x82, 0xbd, 0xb9, 0xc9, 0x73, 0xa3, 0xa7, 0x45, 0x69, 0xac,
	0x79, 0xcc, 0xe6, 0x46, 0x57, 0xf6, 0x6d, 0x2a, 0xaf, 0x94, 0x96, 0x8e, 0x4b, 0xfe, 0xd9, 0x03,
	0x38, 0x97, 0xe5, 0x4a, 0x96, 0x17, 0x2a, 0x97, 0xec, 0x7d, 0x88, 0xac, 0xca, 0x65, 0x65, 0x45,
	0x5e, 0xc4, 0xbd, 0xc3, 0xde, 0xd1, 0x80, 0xb7, 0x04, 0x63, 0xb0, 0x73, 0x2b, 0x45, 0x19, 0xf7,
	0x0f, 0x7b, 0x47, 0x43, 0x4e, 0x63, 0xf6, 0x08, 0x86, 0xb9, 0xd1, 0x76, 0x19, 0x0f, 0x88, 0x74,
	0x80, 0x1d, 0xc0, 0x20, 0x15, 0xb7, 0xf1, 0x0e, 0x71, 0x38, 0xc4, 0x6f, 0x97, 0xa6, 0x2e, 0xe3,
	0xa1, 0xfb, 0x16, 0xc7, 0xec, 0xff, 0x61, 0x94, 0x2b, 0x5d, 0x5b, 0x19, 0x8f, 0x88, 0xf5, 0x08,
	0xf9, 0x4a, 0xce, 0x8d, 0x4e, 0xe3, 0x5d, 0xc7, 0x3b, 0xc4, 0x1e, 0xc3, 0x18, 0x95, 0xf9, 0xb5,
	0xd1, 0x32, 0x1e, 0x93, 0xa4, 0xc1, 0xc9, 0x0d, 0x8c, 0x5f, 0x88, 0x5c, 0xce, 0xac, 0xcc, 0xd9,
	0x3e, 0xf4, 0x55, 0x4a, 0xea, 0x0f, 0x79, 0x5f, 0xa5, 0xb8, 0xb7, 0xbd, 0x2d, 0x64, 0xd0, 0x1b,
	0xc7, 0xa8, 0xf7, 0xdc, 0xd4, 0xda, 0x06, 0xbd, 0x09, 0xb0, 0x0f, 0x00, 0xcc, 0xa5, 0x15, 0x4a,
	0xa3, 0x37, 0x48, 0xfd, 0x01, 0xef, 0x30, 0xb8, 0x92, 0x16, 0xb9, 0x24, 0x2b, 0x22, 0x4e, 0xe3,
	0xe4, 0x77, 0x3d, 0x00, 0x14, 0x72, 0x39, 0x37, 0x25, 0x29, 0x99, 0x89, 0xca, 0x9e, 0xab, 0x85,
	0xa6, 0xb5, 0x07, 0xbc, 0xc1, 0xec, 0x63, 0x38, 0xc0, 0xf1, 0x0b, 0x69, 0xcf, 0x5e, 0x9f, 0x71,
	0x59, 0xd5, 0x99, 0x25, 0xd3, 0x07, 0xfc, 0x0e, 0xcf, 0x0e, 0x61, 0x82, 0xdc, 0x1b, 0x29, 0xaf,
	0xb9, 0x9c, 0x93, 0x27, 0x06, 0xbc, 0x4b, 0x51, 0xb0, 0x8c, 0x15, 0x19, 0xe9, 0xea, 0xfc, 0xd1,
	0x12, 0xc9, 0x3f, 0x7a, 0xb0, 0xf7, 0xaa, 0xce, 0x2f, 0x65, 0xe9, 0x15, 0x3b, 0x80, 0x81, 0xcc,
	0x8c, 0x77, 0x0b, 0x0e, 0x59, 0x0c, 0xbb, 0xda, 0x94, 0xf9, 0x1b, 0xa5, 0xbd, 0x6b, 0x02, 0xc4,
	0xcd, 0x69, 0x25, 0xd4, 0x7a, 0xa6, 0xbd, 0x8f, 0xba, 0x14, 0x7b, 0x02, 0x0f, 0xde, 0x49, 0x79,
	0x7d, 0x11, 0x28, 0x1f, 0xeb, 0x75, 0x12, 0xd7, 0x41, 0xe2, 0x85, 0xc9, 0xd2, 0x17, 0xd2, 0xfa,
	0xe0, 0x77, 0x29, 0xf4, 0x38, 0xc2, 0xe7, 0x37, 0x05, 0x4e, 0x70, 0x79, 0xd0, 0x61, 0x92, 0x3f,
	0xf7, 0x61, 0xf4, 0xe6, 0x97, 0x33, 0x7d, 0x65, 0xd8, 0xd7, 0x01, 0xc4, 0x4a, 0x58, 0x51, 0xbe,
	0xad, 0xcb, 0x8c, 0xec, 0x88, 0x78, 0xe4, 0x98, 0x5f, 0x94, 0x19, 0xc6, 0x66, 0xae, 0xec, 0x2d,
	0x99, 0x12, 0x71, 0x1a, 0x63, 0x26, 0x2d, 0xa4, 0x4e, 0x65, 0xe9, 0x4d, 0xf0, 0x88, 0x7d, 0x05,
	0x76, 0x4d, 0x21, 0xf5, 0x5b, 0x95, 0x92, 0xde, 0x11, 0x1f, 0x21, 0x9c, 0xf9, 0xe8, 0xe9, 0x45,
	0x2d, 0x16, 0x21, 0xc8, 0x0d, 0x66, 0x5f, 0x83, 0x48, 0xab, 0xf9, 0xf5, 0x5b, 0xca, 0x80, 0x91,
	0x13, 0x22, 0xf1, 0x4a, 0xe4, 0x12, 0x3f, 0x2c, 0x4a, 0xb3, 0x52, 0x7a, 0x2e, 0x29, 0x56, 0x11,
	0x6f, 0x30, 0xfb, 0x2a, 0x8c, 0x6b, 0xad, 0x0c, 0x6d, 0x37, 0x26, 0xd9, 0x2e, 0xe1, 0x59, 0x8a,
	0x21, 0xa0, 0xcc, 0x2b, 0x6f, 0xe3, 0xc8, 0x49, 0x3c, 0x44, 0x6b, 0x2b, 0x59, 0x55, 0xfe, 0x33,
	0x70, 0xd6, 0x7a, 0x66, 0x46, 0x39, 0x5d, 0xa1, 0xdb, 0x27, 0xce, 0x5a, 0x1c, 0x27, 0x7f, 0x1b,
	0x40, 0x84, 0x45, 0x50, 0x9e, 0x0a, 0xa5, 0xef, 0x54, 0xc1, 0x01, 0x0c, 0x6a, 0x95, 0x7a, 0xf7,
	0xe0, 0x10, 0xd7, 0xc8, 0x2a, 0x95, 0x7a, 0xdf, 0xd0, 0x18, 0xb9, 0xa2, 0xf2, 0x6e, 0x19, 0x72,
	0x1a, 0xb3, 0x04, 0x86, 0x95, 0x15, 0xd6, 0x79, 0x64, 0xff, 0x78, 0x6f, 0x4a, 0x9b, 0x9c, 0x5b,
	0x61, 0xeb, 0x8a, 0x3b, 0x51, 0x53, 0x19, 0xa3, 0xb6, 0x32, 0xb0, 0xc6, 0x32, 0xb9, 0x92, 0x99,
	0x2f, 0x63, 0x07, 0xd0, 0x64, 0x6f, 0x46, 0x70, 0x86, 0x87, 0x18, 0xad, 0x79, 0x29, 0x71, 0xa3,
	0x88, 0xb2, 0xdd, 0x23, 0x4c, 0x74, 0xcc, 0xfb, 0x97, 0x66, 0xa1, 0x34, 0x79, 0x62, 0xc0, 0x5b,
	0x02, 0x33, 0xc8, 0x03, 0x53, 0x5b, 0xf2, 0xc7, 0x80, 0x77, 0x18, 0x5c, 0x15, 0x2b, 0x7e, 0x96,
	0xc6, 0x7b, 0x2e, 0x07, 0x1c, 0x42, 0x8d, 0xd5, 0xdc, 0xe8, 0xf8, 0x81, 0xb3, 0x14, 0xc7, 0x54,
	0x23, 0x37, 0x45, 0xbc, 0xef, 0x6b, 0xe4, 0xa6, 0xc0, 0xd5, 0x8b, 0x55, 0x71, 0xee, 0x15, 0x7e,
	0x48, 0x0a, 0x77, 0x18, 0x5c, 0xdd, 0xa5, 0x60, 0x7c, 0xe0, 0x12, 0xc9, 0x21, 0x4a, 0x24, 0x29,
	0x16, 0x35, 0xee, 0xfb, 0x9e, 0xeb, 0x55, 0x01, 0xa3, 0x4c, 0x55, 0xaf, 0xe4, 0xbb, 0x4b, 0x25,
	0x63, 0x76, 0xd8, 0x3b, 0x1a, 0xf3, 0x06, 0x27, 0x9f, 0x87, 0x10, 0x2a, 0xad, 0xb6, 0x35, 0x32,
	0x72, 0x72, 0x7f, 0x9b, 0x93, 0x07, 0x5d, 0x27, 0x87, 0xd0, 0xee, 0x74, 0x42, 0x7b, 0x8f, 0xaa,
	0x89, 0x05, 0x46, 0x5b, 0x7e, 0x56, 0x2a, 0xa9, 0x53, 0x2e, 0x3f, 0xaf, 0x65, 0x65, 0xb7, 0xa5,
	0x4f, 0x5e, 0x2d, 0x42, 0xfa, 0xe4, 0xd5, 0x82, 0xda, 0x2a, 0xb6, 0x1e, 0xd7, 0xe5, 0x68, 0xcc,
	0x8e, 0x20, 0x5a, 0xe0, 0x5a, 0x58, 0xb0, 0x94, 0x2e, 0x93, 0x63, 0x98, 0x36, 0x06, 0xf1, 0x56,
	0x98, 0xbc, 0x0f, 0x40, 0xfc, 0xd3, 0x4c, 0xcc, 0xaf, 0x37, 0x77, 0x4b, 0x7e, 0x05, 0x93, 0x8e,
	0x4e, 0x5b, 0x3b, 0xba, 0xf2, 0x8e, 0xf8, 0xe2, 0x5b, 0xff, 0xb6, 0x07, 0xe3, 0x93, 0xa5, 0xb0,
	0xcf, 0x84, 0x15, 0xb8, 0xd4, 0x55, 0x69, 0x72, 0xbf, 0x38, 0x8d, 0xb7, 0x2e, 0xef, 0xed, 0x1f,
	0xb4, 0xf6, 0x63, 0xed, 0x2e, 0x85, 0xd6, 0x32, 0xf3, 0x6e, 0x0e, 0xf0, 0x0b, 0xa8, 0xf2, 0xfb,
	0x01, 0xec, 0x9c, 0x0a, 0x95, 0x75, 0x2c, 0x8c, 0xc8, 0xc2, 0x8f, 0x60, 0x9c, 0x0b, 0x95, 0x5d,
	0x84, 0x73, 0x6b, 0xff, 0x38, 0x9a, 0x9e, 0x7a, 0x82, 0x37, 0xa2, 0xad, 0x31, 0x78, 0x04, 0x43,
	0xbb, 0x94, 0xfe, 0xfc, 0x8a, 0xb8, 0x03, 0x41, 0xff, 0x61, 0xab, 0xff, 0x77, 0x61, 0x22, 0xac,
	0x15, 0xf3, 0x65, 0x2e, 0xb5, 0xad, 0xe2, 0xd1, 0xe1, 0xe0, 0x68, 0x72, 0x1c, 0x4d, 0xc3, 0x31,
	0xca, 0xbb, 0x52, 0x76, 0x18, 0x7a, 0xc0, 0x2e, 0x29, 0x03, 0xa4, 0x0c, 0xb6, 0x00, 0x19, 0x3a,
	0xc0, 0x63, 0x18, 0x57, 0x74, 0x93, 0x98, 0xa5, 0x54, 0xbf, 0x43, 0xde, 0x60, 0x27, 0xc3, 0xce,
	0x3b, 0x73, 0xad, 0x8c, 0x64, 0x0e, 0xb7, 0x09, 0x3c, 0xd9, 0xe8, 0x12, 0x52, 0xa7, 0x74, 0xb4,
	0xed, 0x91, 0x6d, 0x01, 0xe2, 0x7c, 0x55, 0x3d, 0x93, 0x99, 0x2f, 0x5c, 0x07, 0xe8, 0x3c, 0xbf,
	0x5a, 0xcc, 0x52, 0x5f, 0xbb, 0x0e, 0x50, 0x97, 0x14, 0x2b, 0x49, 0x75, 0x3b, 0xe6, 0x34, 0x5e,
	0x0f, 0xce, 0xc1, 0xff, 0x0a, 0xce, 0x4f, 0x7d, 0x8a, 0x9e, 0x0a, 0x3b, 0x5f, 0xb2, 0x0f, 0x60,
	0x27, 0x57, 0x5a, 0x51, 0x8c, 0xd6, 0x3f, 0x21, 0x1e, 0x23, 0x28, 0x14, 0xc5, 0x6a, 0xcc, 0xfb,
	0x42, 0x25, 0x7f, 0xe9, 0x43, 0x44, 0x5f, 0xd2, 0xe1, 0xd5, 0xe9, 0x7a, 0xbd, 0xf5, 0xae, 0xb7,
	0x2d, 0xd9, 0x18, 0xec, 0x88, 0x34, 0x2d, 0x7d, 0xb6, 0xd1, 0x18, 0x3b, 0xd1, 0x55, 0x29, 0x72,
	0xf9, 0x4c, 0x66, 0x56, 0xf8, 0x8c, 0xeb, 0x30, 0x78, 0x22, 0xe7, 0x4a, 0x7f, 0xd6, 0x4e, 0x71,
	0xa7, 0xed, 0x3a, 0x89, 0xbd, 0x34, 0x47, 0xa5, 0xc8, 0xb3, 0xee, 0xb8, 0x6d, 0x09, 0xdc, 0x43,
	0xe9, 0xa2, 0xb6, 0x6e, 0x01, 0xd7, 0xb6, 0x3b, 0x0c, 0x5a, 0x51, 0xac, 0x0a, 0x4a, 0x4a, 0x77,
	0xe1, 0x08, 0x10, 0xbf, 0xb4, 0xcb, 0x52, 0x8a, 0x94, 0xcb, 0xf9, 0x8a, 0xe2, 0x3f, 0xe6, 0x1d,
	0x86, 0x7d, 0x13, 0x46, 0xe4, 0xd8, 0x2a, 0x4e, 0x29, 0xcf, 0x26, 0xd3, 0xd6, 0xb5, 0xdc, 0x8b,
	0x92, 0x14, 0xc6, 0x67, 0xaf, 0xcf, 0x66, 0xb8, 0xdf, 0xb6, 0xfe, 0x73, 0x2b, 0xde, 0xf9, 0x8b,
	0x0a, 0x0e, 0x91, 0xb9, 0xb4, 0xe1, 0x72, 0x82, 0x43, 0x64, 0x0a, 0x53, 0x85, 0x6b, 0x67, 0x61,
	0x2a, 0x72, 0xae, 0xc8, 0xae, 0xc3, 0xb5, 0x13, 0xc7, 0xc9, 0x35, 0xed, 0x42, 0x3e, 0xc1, 0xb4,
	0x49, 0xc9, 0x56, 0xb7, 0x91, 0x03, 0xc8, 0x92, 0x63, 0xfd, 0x6e, 0x0e, 0xd0, 0xe1, 0xa0, 0xdd,
	0x69, 0x39, 0xe6, 0x38, 0x64, 0x1f, 0xc2, 0x88, 0x9c, 0x13, 0x8c, 0x8a, 0xa6, 0x41, 0x7d, 0xee,
	0x05, 0xc9, 0x14, 0xa2, 0xb0, 0x59, 0x85, 0xf3, 0x69, 0xa9, 0x2a, 0xee, 0xb5, 0xf3, 0x49, 0xc6,
	0xbd, 0x20, 0xf9, 0x57, 0x8f, 0x3e, 0xf0, 0x97, 0xc0, 0x47, 0x30, 0xbc, 0x56, 0x59, 0xe6, 0xe6,
	0x0f, 0xb9, 0x03, 0xd8, 0xc8, 0x33, 0xa9, 0x17, 0x76, 0x19, 0xf7, 0x89, 0xf6, 0x68, 0x6b, 0x33,
	0x60, 0xb0, 0xb3, 0xc0, 0xfb, 0xf2, 0x0e, 0xcd, 0xa4, 0x31, 0x46, 0x71, 0x25, 0x4b, 0xca, 0x45,
	0xe7, 0x97, 0x00, 0xb1, 0x36, 0xf2, 0x90, 0xb2, 0xb1, 0xf4, 0x89, 0xde, 0x24, 0x31, 0x6f, 0x85,
	0x1d, 0x53, 0xae, 0xee, 0x31, 0x85, 0x3a, 0x4e, 0xfa, 0x49, 0xbc, 0xf0, 0x1d, 0x27, 0xfd, 0x24,
	0x59, 0x02, 0x70, 0xa1, 0xaf, 0x5f, 0x3a, 0x75, 0x37, 0x23, 0xdc, 0x35, 0xab, 0xb7, 0x6e, 0x56,
	0x29, 0xf4, 0x75, 0xb8, 0xa6, 0xe0, 0xb8, 0x29, 0xc6, 0x9d, 0xed, 0xc5, 0x98, 0xfc, 0xa6, 0x07,
	0xc3, 0x4f, 0xe7, 0xd6, 0x94, 0x5f, 0xee, 0x0c, 0xad, 0xf0, 0xb4, 0xf4, 0x67, 0x28, 0x8e, 0xc3,
	0x05, 0x61, 0xd8, 0x5e, 0x10, 0x62, 0xd8, 0xbd, 0xac, 0x33, 0x95, 0xce, 0x52, 0x5f, 0x4e, 0x01,
	0x26, 0x7f, 0xea, 0x43, 0xf4, 0xb4, 0x56, 0x59, 0x1a, 0x1a, 0xc0, 0x25, 0x81, 0xa0, 0x4c, 0x80,
	0x58, 0x92, 0x34, 0xbc, 0x68, 0xdf, 0x28, 0x2d, 0x81, 0x85, 0x45, 0xe0, 0x65, 0x47, 0xc1, 0x0e,
	0xd3, 0x6d, 0x94, 0x3b, 0xeb, 0x8d, 0xf2, 0xc3, 0xf5, 0x6b, 0xdb, 0x64, 0x4a, 0xca, 0xac, 0xf5,
	0xec, 0x27, 0xf0, 0xe0, 0xb2, 0x94, 0xe2, 0x9a, 0x96, 0x3a, 0x15, 0x37, 0xde, 0x84, 0x75, 0x92,
	0xfd, 0x00, 0x26, 0x45, 0x69, 0xd2, 0x7a, 0x6e, 0x29, 0x2f, 0x76, 0xc9, 0xe7, 0x0f, 0xdc, 0x72,
	0x67, 0x4e, 0xc0, 0xbb, 0x33, 0xd8, 0xf7, 0x21, 0x12, 0xe8, 0xfc, 0x13, 0x99, 0x65, 0xf1, 0x98,
	0xf2, 0xe3, 0xa1, 0x9b, 0xfe, 0x69, 0xa0, 0x79, 0x3b, 0x23, 0xf9, 0x19, 0xec, 0x75, 0xd7, 0x42,
	0x87, 0xa0, 0xb3, 0x2d, 0x19, 0xe5, 0x5f, 0xa1, 0x0d, 0x81, 0x52, 0x6d, 0xf0, 0xad, 0xf4, 0xaa,
	0xce, 0x83, 0xbb, 0x1a, 0x22, 0x79, 0x0a, 0xfb, 0xeb, 0x1b, 0xd1, 0xad, 0x52, 0x66, 0x59, 0xe3,
	0x77, 0x8f, 0xd0, 0x71, 0xa4, 0xc2, 0x2c, 0x0d, 0xaf, 0x1f, 0x0f, 0x93, 0x0b, 0xd8, 0x9b, 0x69,
	0x2b, 0xb3, 0x4c, 0x2d, 0x24, 0xde, 0xdf, 0x37, 0x53, 0xa8, 0x79, 0x3b, 0xf6, 0xef, 0x7f, 0x3b,
	0x0e, 0x36, 0xdf, 0x8e, 0xc9, 0xbf, 0x7b, 0x30, 0x39, 0xb7, 0x75, 0xaa, 0xcc, 0xb9, 0x35, 0xe5,
	0x2d, 0x9b, 0xa2, 0x95, 0xa6, 0xbc, 0xa5, 0xb0, 0xf7, 0x28, 0x44, 0x07, 0xd3, 0xce, 0x04, 0x3a,
	0xe9, 0xdb, 0x29, 0x74, 0x82, 0x20, 0x68, 0xf5, 0xf5, 0xd0, 0xf9, 0xcb, 0x94, 0xb7, 0xf8, 0x10,
	0xf1, 0x47, 0x46, 0x4b, 0xa0, 0xfd, 0xf2, 0xa6, 0x90, 0x73, 0xeb, 0x13, 0xd9, 0x23, 0x3c, 0x93,
	0xe5, 0x4a, 0x6a, 0x72, 0xa3, 0xcb, 0xe7, 0x06, 0xbb, 0x17, 0xb8, 0xa8, 0x8c, 0x0e, 0x2f, 0x73,
	0x87, 0x28, 0xd9, 0x0a, 0x55, 0x99, 0x54, 0xfa, 0xc3, 0x21, 0xc0, 0xe4, 0x0f, 0x83, 0x60, 0x9d,
	0x2b, 0xbb, 0xef, 0xc1, 0x7b, 0xa4, 0xc2, 0xc9, 0x52, 0x94, 0x62, 0x6e, 0x65, 0x59, 0x35, 0x01,
	0xb8, 0x2b, 0xb8, 0x3f, 0x16, 0xf4, 0xaa, 0x33, 0x55, 0x78, 0xa6, 0xd3, 0x98, 0xfd, 0x08, 0x80,
	0xc4, 0x94, 0xca, 0x64, 0xd5, 0xfe, 0xf1, 0x7b, 0xd3, 0xce, 0xee, 0x2e, 0xc7, 0x3b, 0x93, 0xdc,
	0xa5, 0xe1, 0x74, 0xe5, 0x2a, 0x77, 0xcc, 0x1d, 0x60, 0xdf, 0x82, 0x7d, 0xea, 0x68, 0x4a, 0x2f,
	0x5e, 0x8a, 0x4b, 0x99, 0xb9, 0x4b, 0xd0, 0x90, 0x6f, 0xb0, 0xec, 0x27, 0xf0, 0x20, 0x30, 0x67,
	0xa5, 0x29, 0xaa, 0x78, 0x97, 0x72, 0xfa, 0xa0, 0xbb, 0x27, 0x0a, 0xf8, 0xfa, 0x34, 0xf6, 0x43,
	0x80, 0x6a, 0x6e, 0x4a, 0xe9, 0x3e, 0x1a, 0xdf, 0xf3, 0x51, 0x67, 0x0e, 0xfb, 0x0e, 0x8c, 0x2a,
	0xd7, 0xf1, 0x23, 0x9a, 0xbd, 0x6e, 0x16, 0x4a, 0xb8, 0x9f, 0xc0, 0x3e, 0x86, 0x03, 0x7c, 0xae,
	0x8b, 0xec, 0x1c, 0x3f, 0xa7, 0x37, 0xb7, 0xbf, 0x5b, 0xdd, 0xe1, 0x93, 0x13, 0x78, 0xb8, 0xb1,
	0x2b, 0x86, 0xb8, 0x28, 0x4d, 0xd1, 0x96, 0x85, 0x43, 0x74, 0xc4, 0x97, 0xa6, 0x78, 0x2d, 0xb2,
	0x10, 0x0a, 0x0f, 0x93, 0xa7, 0x70, 0xb0, 0xa9, 0x0c, 0x25, 0x25, 0x0e, 0xda, 0xae, 0xe6, 0x21,
	0x7a, 0x9c, 0xec, 0x0a, 0x45, 0x42, 0x20, 0xf9, 0x63, 0x53, 0x04, 0xcf, 0x31, 0xd7, 0x28, 0xa1,
	0x70, 0xd0, 0x7e, 0xef, 0x21, 0x96, 0x07, 0x0d, 0x3b, 0x37, 0xe0, 0xe0, 0xba, 0xe7, 0x81, 0xe7,
	0xed, 0x14, 0x76, 0x08, 0x13, 0x02, 0x3f, 0x2f, 0x2c, 0x1e, 0x6c, 0xfe, 0x97, 0x45, 0x87, 0x42,
	0x87, 0x11, 0x7c, 0xbe, 0x12, 0x59, 0x2d, 0x90, 0xaa, 0xfc, 0xb1, 0x78, 0x87, 0x4f, 0xfe, 0xda,
	0x87, 0x3d, 0xb7, 0x59, 0x7b, 0x12, 0xbb, 0x23, 0xa2, 0xd7, 0x3d, 0x22, 0xb6, 0x1a, 0x89, 0xaa,
	0x5c, 0xa9, 0xb2, 0xb2, 0x67, 0xa5, 0xb9, 0x52, 0x21, 0x75, 0xbb, 0x14, 0x5e, 0xbd, 0x09, 0x72,
	0xf9, 0x4e, 0x94, 0x29, 0x69, 0xb1, 0x7e, 0xf5, 0xee, 0x48, 0xd9, 0x11, 0x3c, 0x9c, 0x1b, 0x6d,
	0x95, 0xae, 0x65, 0xea, 0x97, 0x74, 0xf5, 0xba, 0x49, 0x63, 0xd1, 0x35, 0xd4, 0xd3, 0xfa, 0xf6,
	0x84, 0x9a, 0x94, 0xab, 0xe0, 0xbb, 0x02, 0x36, 0x05, 0x26, 0xea, 0x54, 0x61, 0x8b, 0x6b, 0x4d,
	0xa7, 0xd4, 0x1e, 0xf2, 0x2d, 0x12, 0xf6, 0x6d, 0x88, 0xe4, 0x4d, 0xe1, 0x55, 0x1e, 0x6f, 0xaa,
	0xdc, 0xca, 0x92, 0xbf, 0xf7, 0x00, 0x9c, 0xf3, 0xe8, 0x85, 0xf5, 0x0d, 0x3c, 0x47, 0x65, 0xe1,
	0x7b, 0xdc, 0xa4, 0xe9, 0x71, 0xb2, 0xe0, 0x24, 0x70, 0xff, 0x17, 0x4c, 0xe9, 0x7e, 0xdd, 0x4c,
	0x8e, 0xf7, 0xba, 0x5d, 0x90, 0x3b, 0x11, 0x7b, 0x02, 0x23, 0x2a, 0xe7, 0x2a, 0x1e, 0xd0, 0xce,
	0xeb, 0x93, 0xbc, 0x0c, 0x57, 0xa2, 0x50, 0xfa, 0x7b, 0xc1, 0x5e, 0x37, 0x61, 0xb8, 0x13, 0xb1,
	0x8f, 0x60, 0x54, 0xba, 0x5f, 0x6f, 0x43, 0x7f, 0x90, 0x75, 0x03, 0xcd, 0xbd, 0x30, 0xf9, 0x4f,
	0x1f, 0xfe, 0xcf, 0x09, 0x4e, 0x82, 0xe7, 0xc8, 0x1a, 0xff, 0x1b, 0xc5, 0xff, 0x46, 0xab, 0x55,
	0xfa, 0x65, 0x1a, 0xb3, 0x6f, 0xb2, 0x3b, 0xf7, 0x35, 0xd9, 0xe1, 0x5a, 0x93, 0xa5, 0x9f, 0x11,
	0x14, 0xe9, 0x97, 0xaa, 0xb2, 0xbe, 0x57, 0x75, 0x18, 0x3c, 0xce, 0x1d, 0x3a, 0xa9, 0xcb, 0x12,
	0xdd, 0xe0, 0x9a, 0xf4, 0x3a, 0x89, 0xf9, 0xe4, 0x88, 0x8b, 0xe6, 0x57, 0xaf, 0xbb, 0xcc, 0x6f,
	0xd2, 0xfe, 0xa7, 0x16, 0x7e, 0xda, 0x3c, 0xe9, 0x02, 0x46, 0xdb, 0xdc, 0x18, 0xcf, 0x0f, 0xd7,
	0x77, 0x5a, 0x02, 0x73, 0xcb, 0x81, 0xe7, 0xee, 0x32, 0xe2, 0xb6, 0x71, 0x2f, 0xbc, 0x2d, 0x92,
	0xcb, 0x11, 0xfd, 0x8e, 0xfe, 0xf1, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x03, 0x87, 0xe7,
	0xb2, 0x16, 0x00, 0x00,
}
