// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RpcReqInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcReqInfo) Reset()         { *m = RpcReqInfo{} }
func (m *RpcReqInfo) String() string { return proto.CompactTextString(m) }
func (*RpcReqInfo) ProtoMessage()    {}
func (*RpcReqInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *RpcReqInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcReqInfo.Unmarshal(m, b)
}
func (m *RpcReqInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcReqInfo.Marshal(b, m, deterministic)
}
func (m *RpcReqInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcReqInfo.Merge(m, src)
}
func (m *RpcReqInfo) XXX_Size() int {
	return xxx_messageInfo_RpcReqInfo.Size(m)
}
func (m *RpcReqInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcReqInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RpcReqInfo proto.InternalMessageInfo

func (m *RpcReqInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type RpcRspInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcRspInfo) Reset()         { *m = RpcRspInfo{} }
func (m *RpcRspInfo) String() string { return proto.CompactTextString(m) }
func (*RpcRspInfo) ProtoMessage()    {}
func (*RpcRspInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *RpcRspInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcRspInfo.Unmarshal(m, b)
}
func (m *RpcRspInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcRspInfo.Marshal(b, m, deterministic)
}
func (m *RpcRspInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcRspInfo.Merge(m, src)
}
func (m *RpcRspInfo) XXX_Size() int {
	return xxx_messageInfo_RpcRspInfo.Size(m)
}
func (m *RpcRspInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcRspInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RpcRspInfo proto.InternalMessageInfo

func (m *RpcRspInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type RpcReqData struct {
	Info                 *RpcReqInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Req                  int32       `protobuf:"varint,2,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RpcReqData) Reset()         { *m = RpcReqData{} }
func (m *RpcReqData) String() string { return proto.CompactTextString(m) }
func (*RpcReqData) ProtoMessage()    {}
func (*RpcReqData) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *RpcReqData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcReqData.Unmarshal(m, b)
}
func (m *RpcReqData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcReqData.Marshal(b, m, deterministic)
}
func (m *RpcReqData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcReqData.Merge(m, src)
}
func (m *RpcReqData) XXX_Size() int {
	return xxx_messageInfo_RpcReqData.Size(m)
}
func (m *RpcReqData) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcReqData.DiscardUnknown(m)
}

var xxx_messageInfo_RpcReqData proto.InternalMessageInfo

func (m *RpcReqData) GetInfo() *RpcReqInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *RpcReqData) GetReq() int32 {
	if m != nil {
		return m.Req
	}
	return 0
}

type RpcRspData struct {
	Info                 *RpcRspInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Rsp                  int32       `protobuf:"varint,2,opt,name=rsp,proto3" json:"rsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RpcRspData) Reset()         { *m = RpcRspData{} }
func (m *RpcRspData) String() string { return proto.CompactTextString(m) }
func (*RpcRspData) ProtoMessage()    {}
func (*RpcRspData) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *RpcRspData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcRspData.Unmarshal(m, b)
}
func (m *RpcRspData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcRspData.Marshal(b, m, deterministic)
}
func (m *RpcRspData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcRspData.Merge(m, src)
}
func (m *RpcRspData) XXX_Size() int {
	return xxx_messageInfo_RpcRspData.Size(m)
}
func (m *RpcRspData) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcRspData.DiscardUnknown(m)
}

var xxx_messageInfo_RpcRspData proto.InternalMessageInfo

func (m *RpcRspData) GetInfo() *RpcRspInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *RpcRspData) GetRsp() int32 {
	if m != nil {
		return m.Rsp
	}
	return 0
}

type GameItem struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	ObtainTime           int64    `protobuf:"varint,4,opt,name=obtainTime,proto3" json:"obtainTime,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameItem) Reset()         { *m = GameItem{} }
func (m *GameItem) String() string { return proto.CompactTextString(m) }
func (*GameItem) ProtoMessage()    {}
func (*GameItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *GameItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameItem.Unmarshal(m, b)
}
func (m *GameItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameItem.Marshal(b, m, deterministic)
}
func (m *GameItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameItem.Merge(m, src)
}
func (m *GameItem) XXX_Size() int {
	return xxx_messageInfo_GameItem.Size(m)
}
func (m *GameItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GameItem.DiscardUnknown(m)
}

var xxx_messageInfo_GameItem proto.InternalMessageInfo

func (m *GameItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GameItem) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GameItem) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GameItem) GetObtainTime() int64 {
	if m != nil {
		return m.ObtainTime
	}
	return 0
}

func (m *GameItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*RpcReqInfo)(nil), "RpcReqInfo")
	proto.RegisterType((*RpcRspInfo)(nil), "RpcRspInfo")
	proto.RegisterType((*RpcReqData)(nil), "RpcReqData")
	proto.RegisterType((*RpcRspData)(nil), "RpcRspData")
	proto.RegisterType((*GameItem)(nil), "GameItem")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbf, 0x4e, 0x85, 0x30,
	0x14, 0xc6, 0x53, 0xa0, 0x46, 0xcf, 0x35, 0xc6, 0x34, 0x0e, 0x9d, 0xae, 0x84, 0x89, 0x89, 0x41,
	0x1f, 0xc0, 0xc5, 0xc4, 0xb0, 0x36, 0xbe, 0x40, 0x81, 0x92, 0x74, 0x68, 0x4f, 0xa1, 0x25, 0xd1,
	0xb7, 0x37, 0x2d, 0xe0, 0x65, 0x61, 0xfb, 0xf5, 0x7c, 0x5f, 0x7f, 0xfd, 0x03, 0x8f, 0x3d, 0x1a,
	0x83, 0xb6, 0x71, 0x33, 0x06, 0xac, 0xae, 0x00, 0xc2, 0xf5, 0x42, 0x4d, 0xad, 0x1d, 0x91, 0x3d,
	0x43, 0xbe, 0xe8, 0x81, 0x93, 0x92, 0xd4, 0x0f, 0x22, 0xe2, 0x9e, 0x7b, 0x77, 0x92, 0x7f, 0xec,
	0xfb, 0x3f, 0x65, 0x90, 0xec, 0x15, 0x0a, 0x6d, 0x47, 0x4c, 0x85, 0xcb, 0xdb, 0xa5, 0xb9, 0xa9,
	0x45, 0x0a, 0xa2, 0x60, 0x56, 0x13, 0xcf, 0x4a, 0x52, 0x53, 0x11, 0x71, 0x17, 0x78, 0x77, 0x2a,
	0x58, 0xcf, 0x3e, 0x08, 0xbc, 0xfb, 0x17, 0x78, 0x57, 0xfd, 0xc0, 0xfd, 0x97, 0x34, 0xaa, 0x0d,
	0xca, 0xb0, 0x27, 0xc8, 0xb6, 0xeb, 0x51, 0x91, 0xe9, 0x81, 0x31, 0x28, 0xc2, 0xaf, 0x53, 0x5b,
	0x3d, 0x31, 0x7b, 0x01, 0xda, 0xe3, 0x62, 0x03, 0xcf, 0xd3, 0x70, 0x5d, 0xb0, 0x2b, 0x00, 0x76,
	0x41, 0x6a, 0xfb, 0xad, 0x8d, 0xe2, 0x45, 0x49, 0xea, 0x5c, 0x1c, 0x26, 0xd1, 0x64, 0xa5, 0x51,
	0x9c, 0xa6, 0xa7, 0x27, 0xee, 0xee, 0xd2, 0x17, 0xbe, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xe4,
	0xbb, 0x2b, 0x1a, 0x52, 0x01, 0x00, 0x00,
}
