// Code generated by protoc-gen-go. DO NOT EDIT.
// source: league.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//联盟数据
type LeagueData struct {
	LeagueId             int32    `protobuf:"varint,1,opt,name=leagueId,proto3" json:"leagueId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Declaration          string   `protobuf:"bytes,3,opt,name=declaration,proto3" json:"declaration,omitempty"`
	CreateTime           int64    `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Level                int32    `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Chairman             int32    `protobuf:"varint,6,opt,name=chairman,proto3" json:"chairman,omitempty"`
	GamerList            []int32  `protobuf:"varint,7,rep,packed,name=gamerList,proto3" json:"gamerList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeagueData) Reset()         { *m = LeagueData{} }
func (m *LeagueData) String() string { return proto.CompactTextString(m) }
func (*LeagueData) ProtoMessage()    {}
func (*LeagueData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{0}
}

func (m *LeagueData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeagueData.Unmarshal(m, b)
}
func (m *LeagueData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeagueData.Marshal(b, m, deterministic)
}
func (m *LeagueData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeagueData.Merge(m, src)
}
func (m *LeagueData) XXX_Size() int {
	return xxx_messageInfo_LeagueData.Size(m)
}
func (m *LeagueData) XXX_DiscardUnknown() {
	xxx_messageInfo_LeagueData.DiscardUnknown(m)
}

var xxx_messageInfo_LeagueData proto.InternalMessageInfo

func (m *LeagueData) GetLeagueId() int32 {
	if m != nil {
		return m.LeagueId
	}
	return 0
}

func (m *LeagueData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LeagueData) GetDeclaration() string {
	if m != nil {
		return m.Declaration
	}
	return ""
}

func (m *LeagueData) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *LeagueData) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *LeagueData) GetChairman() int32 {
	if m != nil {
		return m.Chairman
	}
	return 0
}

func (m *LeagueData) GetGamerList() []int32 {
	if m != nil {
		return m.GamerList
	}
	return nil
}

//玩家上线
type OnlineLeague struct {
	Gid                  int32    `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineLeague) Reset()         { *m = OnlineLeague{} }
func (m *OnlineLeague) String() string { return proto.CompactTextString(m) }
func (*OnlineLeague) ProtoMessage()    {}
func (*OnlineLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{1}
}

func (m *OnlineLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineLeague.Unmarshal(m, b)
}
func (m *OnlineLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineLeague.Marshal(b, m, deterministic)
}
func (m *OnlineLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineLeague.Merge(m, src)
}
func (m *OnlineLeague) XXX_Size() int {
	return xxx_messageInfo_OnlineLeague.Size(m)
}
func (m *OnlineLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineLeague.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineLeague proto.InternalMessageInfo

func (m *OnlineLeague) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func init() {
	proto.RegisterType((*LeagueData)(nil), "LeagueData")
	proto.RegisterType((*OnlineLeague)(nil), "OnlineLeague")
}

func init() { proto.RegisterFile("league.proto", fileDescriptor_bdb9cfffc57d92f0) }

var fileDescriptor_bdb9cfffc57d92f0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x4a, 0xc6, 0x30,
	0x10, 0x85, 0x89, 0xf9, 0x53, 0xed, 0xd8, 0x85, 0x0c, 0x2e, 0x82, 0x88, 0x84, 0xae, 0xb2, 0x72,
	0xe3, 0x15, 0xdc, 0x08, 0x05, 0x21, 0x78, 0x81, 0xb1, 0x1d, 0x6a, 0x20, 0x49, 0x25, 0x46, 0x8f,
	0xe9, 0x99, 0xa4, 0x09, 0x6a, 0x77, 0xf3, 0xbe, 0xb7, 0x98, 0xef, 0xc1, 0x10, 0x98, 0xd6, 0x4f,
	0xbe, 0x7f, 0xcf, 0x5b, 0xd9, 0xc6, 0x6f, 0x01, 0x30, 0x55, 0xf0, 0x48, 0x85, 0xf0, 0x06, 0x2e,
	0x5a, 0xfd, 0xb4, 0x68, 0x61, 0x84, 0x55, 0xee, 0x2f, 0x23, 0xc2, 0x29, 0x51, 0x64, 0x7d, 0x66,
	0x84, 0xed, 0x5d, 0xbd, 0xd1, 0xc0, 0xe5, 0xc2, 0x73, 0xa0, 0x4c, 0xc5, 0x6f, 0x49, 0xcb, 0x5a,
	0x1d, 0x11, 0xde, 0x01, 0xcc, 0x99, 0xa9, 0xf0, 0x8b, 0x8f, 0xac, 0x4f, 0x46, 0x58, 0xe9, 0x0e,
	0x04, 0xaf, 0x41, 0x05, 0xfe, 0xe2, 0xa0, 0x55, 0x7d, 0xd7, 0xc2, 0xee, 0x31, 0xbf, 0x91, 0xcf,
	0x91, 0x92, 0xee, 0x9a, 0xc7, 0x6f, 0xc6, 0x5b, 0xe8, 0x57, 0x8a, 0x9c, 0x27, 0xff, 0x51, 0xf4,
	0xb9, 0x91, 0x56, 0xb9, 0x7f, 0x30, 0x1a, 0x18, 0x9e, 0x53, 0xf0, 0x89, 0xdb, 0x2a, 0xbc, 0x02,
	0xb9, 0xfa, 0xa5, 0x4a, 0x2b, 0xb7, 0x9f, 0xaf, 0x5d, 0x5d, 0xfe, 0xf0, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x87, 0xee, 0x4c, 0x0c, 0x09, 0x01, 0x00, 0x00,
}
